version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "6901:6901"
    volumes:
      - ./genymotion:/genymotion
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
